name: Commit Stage # workflow名称
on: push # 当新代码推送到存储库时出发workflow

jobs:
  build: # job的唯一标识符
    name: Build and Test # 一个人性化的job名称
    runs-on: ubuntu-22.04 # 运行job的机器类型
    permissions: # 授予job的权限
      contents: read # 查看当前git仓库的权限
      security-events: write # 向github提交security events的权限
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x mvnw
          ./mvnw install
          


